
-- ARCHITECTURE SPLIT BY YEAR - GENERATE DATA

DROP TABLE IF EXISTS TMP_ARCH_SBY;
SET @saved_cs_client     = @@character_set_client;
SET character_set_client = utf8;
CREATE TABLE `TMP_ARCH_SBY` (
  Year int(11) NOT NULL,
  i386 int(11) NOT NULL,
  x86_64 int(11) NOT NULL,
  Total int(11) NOT NULL
) ENGINE=MyISAM DEFAULT CHARSET=latin1;
SET character_set_client = @saved_cs_client;

INSERT INTO TMP_ARCH_SBY (Year, i386, x86_64, Total) 
SELECT y.YEAR, i.i386, x.x86_64, t.Total
	FROM 
	(
		SELECT 
		DISTINCT YEAR(CREATIONDATE) AS `YEAR` 
		FROM IMAGES a
		WHERE YEAR(CREATIONDATE) > 0
 	) y,
	(
		SELECT 
		DISTINCT YEAR(CREATIONDATE) AS `YEAR`, COUNT(*) as i386
		FROM IMAGES a
		INNER JOIN ARCHITECTURE b
		ON a.ARCHITECTURE_ID = b.ID
		INNER JOIN IMAGETYPE c
        ON a.IMAGETYPE_ID = c.ID
		WHERE b.TYPE = 'i386' -- i386
		AND c.TYPE = 'Machine' -- AMI
		GROUP BY 1
 	) i,
	(
		SELECT 
		DISTINCT YEAR(CREATIONDATE) AS `YEAR`, COUNT(*) as x86_64
		FROM IMAGES a
		INNER JOIN ARCHITECTURE b
		ON a.ARCHITECTURE_ID = b.ID
		INNER JOIN IMAGETYPE c
        ON a.IMAGETYPE_ID = c.ID
		WHERE b.TYPE = 'x86_64' -- x86_64 
		AND c.TYPE = 'Machine' -- AMI
		GROUP BY 1
 	) x,
	(
		SELECT 
		DISTINCT YEAR(CREATIONDATE) AS `YEAR`, COUNT(*) as Total
		FROM IMAGES a
		INNER JOIN ARCHITECTURE b
		ON a.ARCHITECTURE_ID = b.ID
		INNER JOIN IMAGETYPE c
        ON a.IMAGETYPE_ID = c.ID
		WHERE c.TYPE = 'Machine' -- AMI
		GROUP BY 1
 	) t
WHERE y.YEAR = i.YEAR
AND y.YEAR = x.YEAR
AND y.YEAR = t.YEAR
ORDER BY 1;


